### ISSUE TITLE
Highlighting not showing on Windows

### ISSUE THREAD

**Issue by Shaedil** [RRethy/vim-hexokinase#82] opened 2021-04-21 19:55 UTC
### Issue
![image](https://user-images.githubusercontent.com/17773568/115612397-36fafd00-a2b9-11eb-9527-c8a225f1d54f.png)

Highlights do not show at all

### Version
Running Neovim on Windows 10 via GUI, but issue persists in TUI
![image](https://user-images.githubusercontent.com/17773568/115611792-8ab91680-a2b8-11eb-8581-75b532ee2321.png)
`go version go1.16.3 windows/amd64`
Ran `make hexokinase` in plugin directory with no issues

### Reproducible vimrc

```vim
call plug#begin('~/.vim/plugged')
Plug 'RRethy/vim-hexokinase', {'do': 'make hexokinase'}
call plug#end()

filetype plugin on
syntax on
set nocompatible
set encoding=utf8
set termguicolors
colorscheme gruvbox
set background=dark
let g:Hexokinase_highlighters = ['virtual']
```

```css
body {
	background-color: #e8eaf6;
	background-color: deeppink;
	background-color: #f00;
	background-color: oRaNgE;
	background-color: rgb(255, 255, 0);
	background-color: rgba(0, 128, 0, 1);
	background-color: hsl(174,72.1%,56.5%);
	background-color: hsla(274.6,100%,25.5%, 1);
	background-color: #ee82ee;
}
```

**Comment by RRethy** [comment] 2021-04-22 01:22
Which gui?

What's the output of the following (toss in a script and source it):

```vim
echo g:Hexokinase_executable_path
echo executable(g:Hexokinase_executable_path)
echo 'g:Hexokinase_highlighters'..string(g:Hexokinase_highlighters)
echo 'g:Hexokinase_virtualText'..string(g:Hexokinase_virtualText)
echo 'g:Hexokinase_signIcon'..string(g:Hexokinase_signIcon)
echo 'g:Hexokinase_optOutPatterns'..string(g:Hexokinase_optOutPatterns)
echo 'g:Hexokinase_optInPatterns'..string(g:Hexokinase_optInPatterns)
echo 'g:Hexokinase_ftOptOutPatterns'..string(g:Hexokinase_ftOptOutPatterns)
echo 'g:Hexokinase_ftOptInPatterns'..string(g:Hexokinase_ftOptInPatterns)
echo 'g:Hexokinase_palettes'..string(g:Hexokinase_palettes)
echo 'g:Hexokinase_builtinHighlighters'..string(g:Hexokinase_builtinHighlighters)
echo 'g:Hexokinase_highlightCallbacks'..string(g:Hexokinase_highlightCallbacks)
echo 'g:Hexokinase_tearDownCallbacks'..string(g:Hexokinase_tearDownCallbacks)
echo 'g:Hexokinase_refreshEvents'..string(g:Hexokinase_refreshEvents)
echo 'g:Hexokinase_ftDisabled'..string(g:Hexokinase_ftDisabled)
echo 'g:Hexokinase_termDisabled'..string(g:Hexokinase_termDisabled)
```

Does anything change if you run `:HexokinaseTurnOn`?

**Comment by Shaedil** [comment] 2021-04-23 20:47
Using the default nvim-qt gui that ships with Neovim on windows

output:
```
C:\Users\Home PC\.vim\plugged\vim-hexokinase/hexokinase/hexokinase
1
g:Hexokinase_highlighters['virtual']
g:Hexokinase_virtualText'■'
g:Hexokinase_signIcon'■'
g:Hexokinase_optOutPatterns''
g:Hexokinase_optInPatterns'full_hex,rgb,rgba,hsl,hsla,colour_names'
g:Hexokinase_ftOptOutPatterns{}
g:Hexokinase_ftOptInPatterns{}
g:Hexokinase_palettes[]
g:Hexokinase_builtinHighlighters['virtual', 'sign_column', 'background', 'backgroundfull', 'foreground', 'foregroundfull']
g:Hexokinase_highlightCallbacks[function('hexokinase#highlighters#virtual#highlightv2')]
g:Hexokinase_tearDownCallbacks[function('hexokinase#highlighters#virtual#tearDownv2')]
g:Hexokinase_refreshEvents['TextChanged', 'InsertLeave', 'BufRead']
g:Hexokinase_ftDisabled[]
g:Hexokinase_termDisabled0
```

Nothing changes when I run `:HexokinaseTurnOn`

**Comment by RRethy** [comment] 2021-04-23 23:17
Everything looks good so I'm not sure what going on here, suspecting some kind of windows behaviour since I've only used osx and linux.

Does anything show if you use a different highlighter like `let g:Hexokinase_highlighters = ['backgroundfull']`?

What's the output when you run:

**Note**: For `-bg`, use the output from `:echo synIDattr(hlID('Normal'), 'bg')`. For `-files`, use an file with colours (like the file in your description).

```
C:\Users\Home PC\.vim\plugged\vim-hexokinase/hexokinase/hexokinase -simplified -files screenshot_colours.txt -r -ep=full_hex,rgb,rgba,hsl,hsla,colour_names -bg=#16161D -boundary
```

Also, nvim-qt is not the default Neovim GUI, it doesn't have one.

**Comment by Shaedil** [comment] 2021-04-24 18:47
I've tried all the different highlighters but to no effect. 

Here is the output I get from running the command for the file in my description
```
styles.css:10:20-26:#ee82ee
styles.css:9:20-44:#48007f
styles.css:8:20-39:#3edfcf
styles.css:7:20-37:#008000
styles.css:6:20-35:#ffff00
styles.css:5:20-25:#ffa500
styles.css:3:20-27:#ff1493
styles.css:2:20-26:#e8eaf6
```
My fault, Neovim does not have a 'default GUI' but it does have a gui for Windows under Neovim's releases:
![image](https://user-images.githubusercontent.com/17773568/115969277-373e0700-a50a-11eb-9a8f-e9f91d075ebf.png)

**Comment by RRethy** [comment] 2021-04-24 19:51
Going to reopen just in case it's still not fixed but I think the issue had to do with the spaces in the name of your `Home PC` directory. If it works, let me know and I'll close this. If it doesn't work, I don't know what else it could be, you might want to look for other plugins that do the same as hexokinase (there's a few different colorizers).

Also, I didn't know Neovim shipped with nvim-qt TIL.

**Comment by Shaedil** [comment] 2021-04-24 20:07
![image](https://user-images.githubusercontent.com/17773568/115971558-192ad380-a517-11eb-8b65-674b53db9837.png)

It works now, thank you so much! I updated the plugin and it works perfectly fine. It seems like the `Home PC` directory was the root of the issue.

**Closed as completed** 2021-04-24 20:22 UTC

**Comment by RRethy** [comment] 2021-04-25 00:56
Make sure to update again, this fix caused a regression which I just fixed.

**Comment by Shaedil** [comment] 2021-04-25 01:08
I just did, seems like 3 character hex strings are not highlighted.
![image](https://user-images.githubusercontent.com/17773568/115976976-2bba0280-a541-11eb-943b-740e403b56b2.png)

**Comment by RRethy** [comment] 2021-04-25 01:13
Correct, you'll need to specify them in `g:Hexokinase_optInPatterns` with `'triple_hex'` since they are not highlighted by default.

**Comment by Shaedil** [comment] 2021-04-25 01:38
I see, thank you for clarifying. It works fine now.
