### ISSUE TITLE
False positive on CSS id names that start with 3 or 6 digit hex colors e.g. #define

### ISSUE THREAD

**Issue by davidscotson** [RRethy/vim-hexokinase#25] opened 2019-05-12 22:06 UTC
While editing some CSS I noticed an id called #define was getting highlighted as a color, as if it was the color #def and the same seems to be true of other CSS id names that begin with 3 or 6 letter hex colors.

**Comment by RRethy** [comment] 2019-05-14 04:22
Duplicate of https://github.com/RRethy/vim-hexokinase/issues/23.

There is no way to avoid the false positive aside from disabling three digit hex codes from being parsed (see the link on how to do this).

**Closed as completed by RRethy** 2019-05-14 04:22 UTC

**Comment by RRethy** [comment] 2019-08-31 01:43
I just released v2 of vim-hexokinase. It's scrapes asynchronously and has 6 different methods for displaying the colours in a file!

To upgrade, run `git pull && make hexokinase`. For more information on migrating to v2, check out `:h hexokinase-v1-migration`. There are a few fully deprecated options (`:h hexokinase-v1-deprecation`) but almost everything has a v2 alternative. v1 will still work and can be forced by using `:let g:Hexokinase_v2 = 0`.
