### ISSUE TITLE
Internal Vim crash on file write: E315

### ISSUE THREAD

**Issue by timonson** [RRethy/vim-hexokinase#34] opened 2019-09-24 20:08 UTC
Regarding: https://github.com/RRethy/vim-hexokinase/issues/32

I updated hexokinase but the following error still occurs:

When turned off and while saving a file I still get this error on vim: `E315: ml_get: invalid lnum: 39` and after that hexokinase is turned on automatically.

**Comment by RRethy** [comment] 2019-09-25 00:08
That's an internal error in Vim. Not sure what's the cause. Can you post a file where it occurs and the exact sequence of commands.

**Comment by timonson** [comment] 2019-09-25 10:24
It happens for example with the following code saved in a **css** file. The command is *save file*, for example `:w<cr>` or `ZZ`  or  any other way.
It might be that some plugin somehow intervenes but I am no vim expert to be honest. I disabled all my syntax plugins but still got this error. Maybe somebody else can confirm this error?

```css
:root {
  box-sizing: border-box;
}
*,
::before,
::after {
  box-sizing: inherit;
}
body {
  background-color: #eee;
  font-family: Helvetica, Arial, sans-serif;
  border: red;
}
header {
  color: #fff;
  background-color: #0072b0;
  border-radius: 0.5em;
}
main {
  display: block;
}
```

**Comment by RRethy** [comment] 2019-09-25 13:48
I don't get the same behaviour, can you try disabling all other plugins, it could be a plugin modifying the buffer text on writing causing a race condition within the Vim core. Also, you might find it useful to use `:h g:Hexokinase_ftEnabled` and `:h g:Hexokinase_ftDisabled` instead of manually calling `:HexokinaseTurnOff` and `:HexokinaseTurnOn`.

Edit: Also can you post all your configuration for vim-hexokinase.

**Comment by timonson** [comment] 2019-09-26 22:40
It works with `vim -u NONE`, meaning with no configuration file and no plugins. But I am not able to narrow it down right now, my vimrc is too packed. I will let you know when I find more details to narrow it down. Thank you!

**Comment by RRethy** [comment] 2019-11-25 01:36
Closing because this isn't really something I can fix. If you can narrow it down to something specific, then an issue should be opened in github.com/vim/vim and this issue can be tagged.

**Closed as completed by RRethy** 2019-11-25 01:36 UTC
